using Unicorn.Publishing;

namespace Unicorn.Pipelines.UnicornSyncEnd
{
	/// <summary>
	/// Persists the Manual Publish Queue generated by Unicorn for its synched items.
	/// This is required due to the app pool recycle that will be caused by swapping between sync and publish.
	/// </summary>
	public class ManualQueuePersistence : IUnicornSyncEndProcessor
	{
		public void Process(UnicornSyncEndPipelineArgs args)
		{
			ManualPublishQueueHandler.Persist();
		}
	}
}
